control 'SV-234850' do
  title 'The SUSE operating system must be configured to use Coordinated Universal Time (UTC) or Greenwich Mean Time (GMT).'
  desc 'If time stamps are not consistently applied and there is no common time reference, it is difficult to perform forensic analysis.

Time stamps generated by the SUSE operating system include date and time. Time is commonly expressed in UTC, a modern continuation of GMT, or local time with an offset from UTC.'
  desc 'check', 'Verify the SUSE operating system is configured to use UTC or GMT.

Check that the SUSE operating system is configured to use UTC or GMT with the following command:

> timedatectl status | grep -i "time zone"
Time zone: UTC (UTC, +0000)

If "Time zone" is not set to "UTC" or "GMT", this is a finding.'
  desc 'fix', 'Configure the SUSE operating system is configured to use UTC or GMT.

To configure the system time zone to use UTC or GMT, run the following command, replacing [ZONE] with "UTC" or "GMT".

> sudo timedatectl set-timezone [ZONE]'
  impact 0.3
  tag check_id: 'C-38038r618819_chk'
  tag severity: 'low'
  tag gid: 'V-234850'
  tag rid: 'SV-234850r958788_rule'
  tag stig_id: 'SLES-15-010410'
  tag gtitle: 'SRG-OS-000359-GPOS-00146'
  tag fix_id: 'F-38001r618820_fix'
  tag 'documentable'
  tag cci: ['CCI-001890']
  tag nist: ['AU-8 b']

  only_if('This control is Not Applicable to containers (the host controls the system clock and time zone)', impact: 0.0) {
    !%w[docker podman kubepods lxc].include?(virtualization.system)
  }

  describe 'Configured system time zone' do
    subject { command('timedatectl show --property=Timezone --value').stdout.strip }
    it { should be_in input('approved_timezones') }
  end
end
